<?xml version="1.0" encoding="UTF-8" ?>
<NotepadPlus>
    <Session activeView="0">
        <mainView activeIndex="13">
            <File firstVisibleLine="0" xOffset="0" scrollWidth="1" startPos="232" endPos="236" selMode="0" offset="0" wrapCount="1" lang="None (Normal Text)" encoding="-1" userReadOnly="no" filename="D:\Proyectos\Excel\Copia de Seguridad\ContaIPUC_V2\Notas_Desarrollo_Excel_Contaipuc\Liciencias.txt" backupFilePath="" originalFileLastModifTimestamp="-2143617616" originalFileLastModifTimestampHigh="31033180" tabColourId="-1" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="512" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="3" xOffset="0" scrollWidth="4537" startPos="959" endPos="949" selMode="0" offset="0" wrapCount="1" lang="Markdown (preinstalled)" encoding="-1" userReadOnly="no" filename="D:\Proyectos\Excel\Copia de Seguridad\ContaIPUC_V2\Notas_Desarrollo_Excel_Contaipuc\Notas_V02.MD" backupFilePath="" originalFileLastModifTimestamp="-131368780" originalFileLastModifTimestampHigh="31061287" tabColourId="-1" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="512" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="3" xOffset="0" scrollWidth="3913" startPos="1151" endPos="1156" selMode="0" offset="0" wrapCount="1" lang="None (Normal Text)" encoding="-1" userReadOnly="no" filename="D:\Proyectos\Excel\Copia de Seguridad\ContaIPUC_V2\Notas_Desarrollo_Excel_Contaipuc\Debug_RecordSet_inmediato.txt" backupFilePath="" originalFileLastModifTimestamp="-1848185101" originalFileLastModifTimestampHigh="31060160" tabColourId="-1" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="512" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="3" xOffset="0" scrollWidth="3040" startPos="832" endPos="832" selMode="0" offset="0" wrapCount="1" lang="None (Normal Text)" encoding="-1" userReadOnly="no" filename="D:\Proyectos\Excel\Copia de Seguridad\ContaIPUC_V2\Notas_Desarrollo_Excel_Contaipuc\Notas de Migracion.txt" backupFilePath="" originalFileLastModifTimestamp="-772759252" originalFileLastModifTimestampHigh="31062409" tabColourId="-1" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="512" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="3014" startPos="6533" endPos="6639" selMode="0" offset="0" wrapCount="1" lang="None (Normal Text)" encoding="-1" userReadOnly="no" filename="D:\Proyectos\Excel\Copia de Seguridad\ContaIPUC_V2\Notas_Desarrollo_Excel_Contaipuc\Requermiento Desarrollo de funcion de consulta por fechas.txt" backupFilePath="" originalFileLastModifTimestamp="-344335274" originalFileLastModifTimestampHigh="31060541" tabColourId="-1" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="512" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="3014" startPos="1371" endPos="1348" selMode="0" offset="0" wrapCount="1" lang="C++" encoding="-1" userReadOnly="no" filename="D:\Proyectos\Excel\Copia de Seguridad\ContaIPUC_V2\Notas_Desarrollo_Excel_Contaipuc\borrame\objetos.txt" backupFilePath="" originalFileLastModifTimestamp="627486060" originalFileLastModifTimestampHigh="31060215" tabColourId="-1" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="512" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="3014" startPos="840" endPos="815" selMode="0" offset="0" wrapCount="1" lang="None (Normal Text)" encoding="-1" userReadOnly="no" filename="D:\Proyectos\Excel\Copia de Seguridad\ContaIPUC_V2\Notas_Desarrollo_Excel_Contaipuc\estructura de informes.txt" backupFilePath="" originalFileLastModifTimestamp="1195914890" originalFileLastModifTimestampHigh="31060204" tabColourId="-1" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="512" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="3" xOffset="0" scrollWidth="3014" startPos="38" endPos="38" selMode="0" offset="0" wrapCount="1" lang="None (Normal Text)" encoding="-1" userReadOnly="no" filename="D:\Proyectos\Excel\Copia de Seguridad\ContaIPUC_V2\Notas_Desarrollo_Excel_Contaipuc\Metodo para generar Informes en hoja tama&#x00F1;o carta y oficio.txt" backupFilePath="" originalFileLastModifTimestamp="572876611" originalFileLastModifTimestampHigh="31060215" tabColourId="-1" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="512" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="3014" startPos="278" endPos="239" selMode="0" offset="0" wrapCount="1" lang="None (Normal Text)" encoding="-1" userReadOnly="no" filename="D:\Proyectos\Excel\Copia de Seguridad\ContaIPUC_V2\Notas_Desarrollo_Excel_Contaipuc\Reporte Auxiliar POr a&#x00F1;o.txt" backupFilePath="" originalFileLastModifTimestamp="-343202784" originalFileLastModifTimestampHigh="31060541" tabColourId="-1" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="512" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="3014" startPos="675" endPos="675" selMode="0" offset="0" wrapCount="1" lang="None (Normal Text)" encoding="-1" userReadOnly="no" filename="D:\Proyectos\Excel\Copia de Seguridad\ContaIPUC_V2\Notas_Desarrollo_Excel_Contaipuc\Select a la bd.txt" backupFilePath="" originalFileLastModifTimestamp="1205611393" originalFileLastModifTimestampHigh="31060276" tabColourId="-1" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="512" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="3014" startPos="886" endPos="886" selMode="0" offset="0" wrapCount="1" lang="None (Normal Text)" encoding="-1" userReadOnly="no" filename="D:\Proyectos\Excel\Copia de Seguridad\ContaIPUC_V2\Notas_Desarrollo_Excel_Contaipuc\borrame\nuevo 1.txt" backupFilePath="" originalFileLastModifTimestamp="-342806534" originalFileLastModifTimestampHigh="31060541" tabColourId="-1" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="512" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="3014" startPos="0" endPos="0" selMode="0" offset="0" wrapCount="1" lang="None (Normal Text)" encoding="-1" userReadOnly="no" filename="D:\Proyectos\Excel\Copia de Seguridad\ContaIPUC_V2\Notas_Desarrollo_Excel_Contaipuc\codigo para genrar informes por meses y a&#x00F1;os.txt" backupFilePath="" originalFileLastModifTimestamp="-1587573604" originalFileLastModifTimestampHigh="31060290" tabColourId="-1" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="512" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="5467" startPos="109" endPos="109" selMode="0" offset="0" wrapCount="1" lang="None (Normal Text)" encoding="-1" userReadOnly="no" filename="D:\Inetum\FXA\2023\General\Notas Generales\notas capacitacion.txt" backupFilePath="" originalFileLastModifTimestamp="1035540278" originalFileLastModifTimestampHigh="31077711" tabColourId="-1" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="512" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="1465" startPos="645" endPos="645" selMode="0" offset="0" wrapCount="1" lang="Markdown (preinstalled)" encoding="-1" userReadOnly="no" filename="D:\Proyectos\PHP\Ruby\Readme.MD" backupFilePath="" originalFileLastModifTimestamp="1874485688" originalFileLastModifTimestampHigh="31089982" tabColourId="-1" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="512" mapWrapIndentMode="-1" mapIsWrap="no" />
        </mainView>
        <subView activeIndex="0" />
    </Session>
</NotepadPlus>
